# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maciej Świętochowski - Blog
email: m@swietochowski.eu
description: > # this means to ignore newlines until "baseurl:"
  Articles about software-related concepts that I encounter both
  privately and professionally. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.swietochowski.eu" # the base hostname & protocol for your site
twitter_username: mswietochowski
github_username:  mswietochowski

# Build settings
markdown: kramdown
excerpt_separator: <!--MORE-->

#various
dateformat: "%b %-d, %Y"
